### ISSUE TITLE
Add VS Code "start script" setup to the Section 0

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#101]
Document the setup of VS Code to allow "code ." to work in the terminal on mac as it isn't setup by default

**Comment by JohanBester** [comment]
Hi Folks, we just identified an issue with VS Code on Macs.
It seems using
code .
on a Mac does not work.
There are extra steps that are needed.
There are steps to get this working on Mac. We might want to put this in the curriculum.
Here is a link to get it working...
https://vscode.readthedocs.io/en/latest/setup/mac/
