### ISSUE TITLE
Add Homework folder to each week

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#13]
Each folder should contain:
Goal: Mastery of these Skills
Goal: Capstone work
HOMEWORK

**Comment by JohanBester** [comment]
@matsinet Hi Matt, I cannot find the spelling issues you commented on in my repo. I have committed and pushed my work again.
If the changes are still not there/visible, then we should delete this pull request and make a new one so that it can find the most recent and up to date data.
