### ISSUE TITLE
Rename Weeks to Sections and daily portions to Lessons

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#14]
Dependent on the completion of issue #13

**Comment by matsinet** [comment]
@matsinet might be able to use PHPStorm to refactor folders and files which will update all references thus reducing effort.

**Comment by JohanBester** [comment]
I do not know PHPStorm, but someone else recently recommended it to me to do something similar on another project I'm working on. Maybe this is a sign that I should learn some about PHPStorm.  :)
