### ISSUE TITLE
Create an ending quiz

### ISSUE THREAD

**Issue by cbrantley4** [savvy-coders/sc-curriculum#162]
Create a quiz that checks what material the students have retained from the cohort. 

**Whoever picks this up should discuss/query the entire staff, TAs and Instructors on what should be covered and possible questions.**

We should determine if there is a good way to deliver these "quizzes" to not allow the student to cheat, specifically during the exit quiz.

**Comment by matsinet** [comment]
On Hold as this needs to be revisited

**Comment by matsinet** [comment]
We are abandoning the practice of end of cohort quiz for the use of show and tell to prove the student understands what is being taught.
