### ISSUE TITLE
Refactor Orientation documentation in Section 0

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#187]
Merge OS specific documentation
~~Remove zsh instructions on Mac OS~~
Remove iTerm2 instructions

The idea is to reduce the number of files to maintain and reduce the duplication of instructions.

Coordinate with recruiting staff (Nathaniel) in regards to what is handed out prior the cohort.
Replace any references to a specific person (Dez) with "Recruiting Staff"

Archive or remove the instructions for the installation of the local mongodb server:
https://github.com/savvy-coders/sc-curriculum/blob/master/Section00/0.1.4-WINDOWS-WALKTHRU.md

**Comment by matsinet** [comment]
Here is what Nathaniel hands out during the recruiting process:
[FS Orientation Agenda.pdf](https://github.com/savvy-coders/sc-curriculum/files/7935967/FS.Orientation.Agenda.pdf)
[FS Next Steps Prework.pdf](https://github.com/savvy-coders/sc-curriculum/files/7935968/FS.Next.Steps.Prework.pdf)

**Comment by drod1107** [comment]
Some redundancy remains between the Section 0 files and further refactoring/editing may be advisable. Will refactor/edit post review, before merge.
