### ISSUE TITLE
Enhance Git oriented material

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#19]
Git portions of the curriculum should be enhanced including the following:

- Git commands
- Workflow strategies (branching/forking)
- Git Bash
- GitHub
- Git integrations in VS Code
- Hack night activities

**Comment by JohanBester** [comment]
I found a great resource from my favorite source. This is an article in Git and Branches -- sort of a cheat sheet.
https://www.freecodecamp.org/news/how-to-use-branches-in-git/
