### ISSUE TITLE
Update Font Awesome to latest version (6)

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#205]
Update all references to font awesome to the latest version and update any code necessary to support.

Update the curriculum and repositories respectively
Please add pull request links here as each one is created
- [x] Update [Curriculum](https://github.com/savvy-coders/sc-curriculum)
  - [x] PR development branch [PR]()
- [x] Update [Teacher's Guide](https://github.com/savvy-coders/sc-js-teachers-guide)
  - [ ] PR development branch [PR]()
- [ ] Update example repos
  - [x] [Stateless-SPA-example](https://github.com/savvy-coders/Stateless-SPA-example)
    - [ ] PR development branch [PR]()
    - [ ] PR final branch [PR]()
  - [x] [State-Driven-SPA-example](https://github.com/savvy-coders/State-Driven-SPA-example)
    - [x] PR development branch [PR]()
    - [x] PR APIsAndAxios branch [PR]()
  - [ ] [SPA-example-with-Axios](https://github.com/savvy-coders/SPA-example-with-Axios)
    - [x] PR development branch [PR]()
  - [ ] [SPA-example-with-Express-and-Mongo](https://github.com/savvy-coders/SPA-example-with-Express-and-Mongo)
    - [x] PR development branch [PR]()

**Comment by H-Matzy** [comment]
Awaiting Auth on Stateless-SPA-example and MR approval on rest of list
