### ISSUE TITLE
Remove link to section 3.4 from the README.md

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#219]
Remove link to section 3.4 from the README.md as it doesn't exist anymore.

**Comment by rohinish404** [comment]
please tell only the link should be removed or the whole line??

**Comment by matsinet** [comment]
> please tell only the link should be removed or the whole line??

@rohinish404 

The whole line needs to be removed.

May I ask how you found this issue and repository?

**Comment by rohinish404** [comment]
Yeah, i was just searching for some good first issues so then i came across this issue. I was using a website named issuehub.
