### ISSUE TITLE
Rename "state" to "store" when referring to the global level

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#221]
In index.js during the import of the view and component state files it should be named store instead of state.

`import * as state from "./store";`
should be:
`import * as store from "./store";`

Then when referencing a individual view state it would be accessed using `store.Home`.
When passing a single view or component state, currently `st`, should be renamed to `state`

Please add pull request links here as each one is created
- [x] Update curriculum [sc-curriculum](https://github.com/savvy-coders/sc-curriculum)
- [x] Update example repos
  - [x] [State-Driven-SPA-example](https://github.com/savvy-coders/State-Driven-SPA-example)
    - [x] [PR development branch: Change 'state' to 'store'](https://github.com/savvy-coders/State-Driven-SPA-example/pull/14)
    - [x] PR APIsAndAxios branch
  - [x] [SPA-example-with-Axios](https://github.com/savvy-coders/SPA-example-with-Axios)
    - [x] PR development branch
    - [x] PR final branch
  - [x] [SPA-example-with-Express-and-Mongo](https://github.com/savvy-coders/SPA-example-with-Express-and-Mongo)
    - [x] PR development branch
    - [x] PR final branch
   - [x] Stateless SPA

**Comment by RishiKumarRay** [comment]
how many references needs to changes?

**Comment by matsinet** [comment]
@RishiKumarRay I am sorry but this ticket requires knowledge of several repositories and would not by wise for someone outside our organization to pick up.   I marked it as `good first issue` thinking one of our newer staff members would pick it up.
