### ISSUE TITLE
Updates for Section 1

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#253]
Section 1 -  [Read here "How to create a LinkedIn profile"](https://www.dummies.com/social-media/social-media-design/how-to-create-a-linkedin-profile/)  Should be the this link:  [Signing Up to Join LinkedIn | LinkedIn Help](https://www.linkedin.com/help/linkedin/answer/2964/signing-up-to-join-linkedin?lang=en)

We have an example of the Intro, but the Elevator comes first.  Please use this example:  Hi! My name is Laurie Wilson. I have a background in IT Recruiting, Sales, and Leadership, but I have always been interested in coding. A co-worker who graduated from Savvy Coders had good things to say about the program, so I attended preview night and knew right away that the program was for me.
[Full Stack Capstone Checklist.docx](https://github.com/savvy-coders/sc-curriculum/files/8200358/Full.Stack.Capstone.Checklist.docx)

For my capstone project, I decided to create a meal prep website that is meant for busy people who do not have a lot of time to devote to cooking. 

Also, SG and I want to incorporate the Capstone Checklist into Section 1.  Attached (Should be converted to markdown or PDF)

[Full Stack Capstone Checklist.docx](https://github.com/savvy-coders/sc-curriculum/files/8200362/Full.Stack.Capstone.Checklist.docx)
.

**Comment by drod1107** [comment]
[FS Next Steps Prework (3).pdf](https://github.com/savvy-coders/sc-curriculum/files/8248794/FS.Next.Steps.Prework.3.pdf)

## From Nathaniel------------^
Also per Nathaniel, this is what is sent out regarding the preview night for FS:

### TOMORROW NIGHT
Instructions for tomorrow night's Savvy Coders Interactive Virtual Crash Course -  Learn JavaScript!
Greetings!
We are looking forward to our VIRTUAL Crash Course tomorrow evening with you! Here are some basic instructions for you to follow before the Crash Course tomorrow night at 6pm CST! The ZOOM information is below & we will see you then!
1. Please Download Chrome as your browser
2. Please navigate to:
http://bit.ly/savvycoders_preview_registration 3. After downloading Chrome, please navigate to:
http://bit.ly/glitch-savvycoders
4. Click on the “Sign in” button on the top right
5. Setup an  ccount
6. Please have your laptop ready to go when the preview starts!
We will be u ing this site during class and want to get started right away so please try to have thi  done before you come  o the crash course. 
If you have any issues, please contact us as soon as you can so we can address them. 
Please TE T Dez at [618.207.7842](tel:6182077842) or email [dez@savvycoders.com](mailto:dez@savvycoders.com) if there are any ssues!
We will see you soon! 
The Savvy Coders Team
Topic: Full Stack Preview
Time: This is a recurring meeting Meet anytime
Join Zoom Meeting
 
https://zoom.us/j/99147208262?pwd=TmpyanpUdUFUWEVJN3hpNG5DUVM3QT09

**Comment by matsinet** [comment]
@drod1107  What is the above comment regarding?   It doesn't appear to have any relevance to this ticket.

**Comment by drod1107** [comment]
> @drod1107 What is the above comment regarding? It doesn't appear to have any relevance to this ticket.

@matsinet good call. I mistakenly thought this was the ticket for the Orientation documentation. Clearly still working on reading comprehension; this belongs over here:

https://github.com/savvy-coders/sc-curriculum/issues/187

...where you've done had it for a good minute, so don't mind me, and carry on. 😬
