### ISSUE TITLE
Update Skills and Culture document

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#284]
**Is your feature request related to a problem? Please describe.**
Add a link to the Skills and Culture document that is on the Google Drive in the appropriate place
https://drive.google.com/file/d/1NvNQhmcCbsAnB8ZxML61VYSiWEckJpyd/view

Add link to  [0.1.3-StudentGuidelinesAndEscalationProcess.md](https://github.com/savvy-coders/sc-curriculum/blob/master/Section00/0.1.3-StudentGuidelinesAndEscalationProcess.md) in in the Over Communication section on 0.0

**Matt to provide link**

**Describe the solution you'd like**

> Matt,
> 
> I did add this, just now, to the google drive that SG created for us to house all the docs.
> 
> I need to add this to the curriculum when I do my Elevator, Linkedin, Resume, and Intro training.  It's a document that talks about what employers want, via soft skills/culture, in an employee.  Can you add it?
> 
> --
> Regards,
> 
> Laurie Wilson

**Update the curriculum and repositories respectively**
Please add pull request links here as each one is created
- [ ] Update [Curriculum](https://github.com/savvy-coders/sc-curriculum)
  - [ ] PR development branch [PR]()

**Comment by JohanBester** [comment]
Completed
