### ISSUE TITLE
Update section 6.3

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#296]
**Is your feature request related to a problem? Please describe.**
Update section 6.3 with the following from comments during cohort instruction

Lesson 6.3 Activity 1

- step 4
  - why do we create an array and then replace it in step 9 without using it?
  - (Delete step 4 and reverse order of step 8 and 9)
- step 8 
  - change `render(store.Home)`  with `render()`
    - The `store.Home` is the default value for the argument so there is no need to pass it.
- step 9 
  - change `state.Header` to `state.header`
  - change `el` parameter to `link`

**Update the curriculum and repositories respectively**
Please add pull request links here as each one is created
- [x] Update [Curriculum](https://github.com/savvy-coders/sc-curriculum)
  - [x] PR development branch [PR]()

**Comment by JohanBester** [comment]
Updated section 6 accorind to the notes and made a PR to pull this into Development
