### ISSUE TITLE
Update Jasmine Unit Testing section 10.3

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#302]
**Describe the solution you'd like**
Update Jasmine Unit Testing section 10.3 per @JohanBester 

**Update the curriculum and repositories respectively**
Please add pull request links here as each one is created
- [x] Update [Curriculum](https://github.com/savvy-coders/sc-curriculum)
  - [x] PR development branch [PR]()

**Comment by JohanBester** [comment]
Done done
