### ISSUE TITLE
Add for ... in loop to section 3.2

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#305]
**Is your feature request related to a problem? Please describe.**
Add explanation of the use of for ... in loop to section 3.2

**Update the curriculum and repositories respectively**
Please add pull request links here as each one is created
- [ ] Update [Curriculum](https://github.com/savvy-coders/sc-curriculum)
  - [ ] PR development branch [PR]()

**Comment by JohanBester** [comment]
[JavaScript_for_in_Loop.pdf](https://github.com/savvy-coders/sc-curriculum/files/8962944/JavaScript_for_in_Loop.pdf)

Here is some content for the for..in loop
