### ISSUE TITLE
Update repos to use of HTML Tagged Template Literals

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#34]
Here is a link as reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

@matsinet has experimented with it using the following:

- VS Code
    - https://marketplace.visualstudio.com/items?itemName=bierner.lit-html
  
- Settings
    "emmet.includeLanguages": {
         "javascript": "html"
    },

- NPM package
    - https://www.npmjs.com/package/html-literal

**Comment by JohanBester** [comment]
This is a great Idea! I love it! I'm gonna try installing it on a few projects to play with. I see this being an excellent aid to students as they develop their SPAs. Working with HTML in JS modules is a pain without intellisense.

**Comment by matsinet** [comment]
Repos to be updated:

- savvy-coders/savvy-starter
