### ISSUE TITLE
Orientation - Update MAC Specific Instructions 0.0.1-OS-Specific-Instructions.md

### ISSUE THREAD

**Issue by mjwebb1993** [savvy-coders/sc-curriculum#348]
https://github.com/savvy-coders/sc-curriculum/blob/master/Section00/0.1.1-OS-Specific-Instructions.md

For Step 3, "Follow the directions in this link", we should pull all of the desired instructions from the linked page (https://www.freecodecamp.org/news/how-to-configure-your-macos-terminal-with-zsh-like-a-pro-c0ab3f3c1156/) and include them into the steps so that everything is on a single page. Also make sure to include step that ensures Path is shown.

If Deemed Necessary, we could create two specific Development Environment

**Comment by matsinet** [comment]
Closing this ticket as I believe it is out of date.
