### ISSUE TITLE
Template Idea

### ISSUE THREAD

**Issue by Foreveryoungx** [savvy-coders/sc-curriculum#67]
https://github.com/Foreveryoungx/SPA-Template

**Comment by matsinet** [comment]
This will be resolved with ticket: https://github.com/savvy-coders/sc-js-teachers-guide/issues/1
The teacher's guide and supporting repos with be updated to give a starting and ending point for each section where appropriate.
This should give the teachers something to demo and the students a starting point for each section.
Thanks for the ticket.
