### ISSUE TITLE
ADD solution for including images in the SPA

### ISSUE THREAD

**Issue by JohanBester** [savvy-coders/sc-curriculum#82]
Add solution for including images in the SPA according the the notes pinned in Slack at https://savvycoders.slack.com/archives/C01DANT64TW/p1616016887012600

Place any assets you may want to include in your project in the folder at the root of the project such as "assets" or "assets/img" so that the path from the root of the project for a image might be "assets/img/myImage.jpg"

Then in the view file that includes the HTML template literal:
Import the image from the assets folder just like you would import a javascript module:  
```
import myImage from '../../assets/img/myImage.jpg';
```

To use the image imported you reference to variable in the src attribute of the img tag: 
```
<img src="${myImage}" />
```

**Here is an example view file:**
```
import html from 'html-literal';
import sharksImage from '../../assets/IMG_20150708_133155453.jpg';
export default () => html`
<section id="jumbotron">
  <h2>Savvy Coders Jan. 2020 Cohort</h2>
  <a href="">"Call to Action" "Button"</a>
</section>
<img class="cover-img" src="${sharksImage}" />
`;
```

**Comment by matsinet** [comment]
Add to Section 6.2 under the activity in step 16
https://github.com/savvy-coders/sc-curriculum/blob/master/Section06-SinglePageApplication/6.2-SPAComponents.md#activity-functional-components
